# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180816_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcar',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
