# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shopcar_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(default='user_pic/IMG_0766.PNG', upload_to='user_pic'),
        ),
    ]
